version: '3'
services:
  web:
    build:
      context: ./app
    links:
      - mysql
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:root@mysql/taxi
  mysql:
    image: "mysql:5.7"
    ports:
      - "32000:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro
  front:
    build:
      context: ./front
    volumes:
      - ./front:/app
    ports:
      - '8080:8080'
    environment:  
      - BACKEND_URL=http://localhost:5000/